blog_user:
    resource: "@BlogUserBundle/Resources/config/routing.yml"
    prefix:   /user/

blog_comment:
    resource: "@BlogCommentBundle/Resources/config/routing.yml"
    prefix:   /

blog_app:
    resource: "@BlogAppBundle/Resources/config/routing.yml"
    prefix:   /

blog_post:
    resource: "@BlogPostBundle/Resources/config/routing.yml"
    prefix:   /

